### PR TITLE
Add ability to show/hide event types in Events list in viz

### PR DESCRIPTION
**Pull request by emichael**
Adds a toggle pane on the side that shows/hides the messages in each node's inbox area.

This commit _might_ address #59, but I'm not sure.

### CODE REVIEW

**Comment by emichael** [comment]
@wilcoxjay is this what you had in mind for #59?

image

I'm just now realizing you might have meant the list on the right side of the window. What sort of UI were you thinking?

**Comment by wilcoxjay** [comment]
Ah, yeah, I actually meant the right-hand pane. The use case is a failing random DFS search trace that is like 50 messages long and most of them are Pings I don't care about :)

**Comment by emichael** [comment]
Ahhhh, gotcha. Any ideas for the UI for setting the filters? Should this be in the left side pane like I have these settings or maybe a pop up menu with something similar (and where would you open the pop up menu)?

**Comment by wilcoxjay** [comment]
I think the simplest thing is just more checkboxes on the far left.

**Comment by emichael** [comment]
Okay, I think this implementation makes sense now. @wilcoxjay want to try it out and kick the tire on it?

**Comment by wilcoxjay** [comment]
Looks good to me! If you try to filter out an event that matches the current state you're looking at, then it is not filtered but still shown. But I think this is probably good behavior anyway.

**Comment by emichael** [comment]
Yes, that was intentional. 

Alright, cool. I'll merge this. Let me know how it works and if people find it useful

**Pull request merged**
