### PR TITLE
Compute client waiting time without including testing framework time

### PR DESCRIPTION
**Pull request by emichael**
This commit adds a private field to RunState to track when the system under test was most recently stopped. Then, when checking ClientWorkers' maximum wait times, we use that time as the basis for computing the maximum wait time.

This is a modification of @wilcoxjay's original fix, but I think it's a little bit cleaner to not force every test to call a specific method before calling `assertMaxWaitTimeLessThan`.

### CODE REVIEW

**Comment by emichael** [comment]
Fixes #48.

**Comment by emichael** [comment]
This is totally untested. Will need to add some sort of testing later or at least verify by hand that this still works.

@wilcoxjay for some reason I can't add you as a reviewer, but what do you think?

**Comment by emichael** [comment]
Replaces #50.

**Comment by wilcoxjay** [comment]
Looks great! I like this approach a lot more.

**Comment by wilcoxjay** [comment]
I ran into this problem again today. Can we merge this?

**Pull request merged**
